export const mockData = [
  {
    id: "1",
    timeSend: "2024-01-01T10:30:00Z",
    channel: "Website",
    question: "What are your business hours?",
    answer: "Our business hours are from 9 AM to 5 PM, Monday through Friday.",
    language: "English",
    purpose: "Customer Inquiry",
    subpurpose: "General Inquiry",
    user: "john.doe@example.com",
    userId: "user123",
  },
  {
    id: "2",
    timeSend: "2024-01-02T11:00:00Z",
    channel: "Mobile App",
    question: "How can I track my order?",
    answer:
      "You can track your order by logging into your account and navigating to the 'Orders' section.",
    language: "English",
    purpose: "Order Support",
    subpurpose: "Tracking",
    user: "jane.smith@example.com",
    userId: "user456",
  },
  {
    id: "3",
    timeSend: "2024-01-02T14:45:00Z",
    channel: "Email",
    question: "Can I change my shipping address after placing the order?",
    answer:
      "Once an order is placed, the shipping address cannot be changed. Please contact support for assistance.",
    language: "English",
    purpose: "Order Support",
    subpurpose: "Shipping",
    user: "michael.jones@example.com",
    userId: "user789",
  },
  {
    id: "4",
    timeSend: "2024-01-03T08:15:00Z",
    channel: "Website",
    question: "How do I reset my password?",
    answer:
      "To reset your password, click on 'Forgot Password' on the login page and follow the instructions.",
    language: "English",
    purpose: "Account Management",
    subpurpose: "Password Reset",
    user: "emily.white@example.com",
    userId: "user101",
  },
  {
    id: "5",
    timeSend: "2024-01-04T16:00:00Z",
    channel: "Mobile App",
    question: "What payment methods are accepted?",
    answer: "We accept credit cards, PayPal, and Apple Pay.",
    language: "English",
    purpose: "Payment Support",
    subpurpose: "Payment Methods",
    user: "david.perez@example.com",
    userId: "user202",
  },
  {
    id: "6",
    timeSend: "2024-01-05T09:30:00Z",
    channel: "Chatbot",
    question: "How do I return an item?",
    answer:
      "To return an item, go to 'My Orders' and select 'Return Item'. Follow the prompts to complete the process.",
    language: "English",
    purpose: "Returns Support",
    subpurpose: "Return Process",
    user: "olivia.green@example.com",
    userId: "user303",
  },
  {
    id: "7",
    timeSend: "2024-01-06T10:45:00Z",
    channel: "Website",
    question: "Can I update my billing information?",
    answer:
      "Yes, you can update your billing information from the 'Account Settings' section.",
    language: "English",
    purpose: "Account Management",
    subpurpose: "Billing Information",
    user: "susan.martin@example.com",
    userId: "user404",
  },
  {
    id: "8",
    timeSend: "2024-01-07T15:30:00Z",
    channel: "Email",
    question: "Do you offer gift cards?",
    answer:
      "Yes, we offer gift cards in various denominations. You can purchase them through our website.",
    language: "English",
    purpose: "Sales Inquiry",
    subpurpose: "Gift Cards",
    user: "joseph.lee@example.com",
    userId: "user505",
  },
  {
    id: "9",
    timeSend: "2024-01-08T12:00:00Z",
    channel: "Mobile App",
    question: "How can I cancel my subscription?",
    answer:
      "To cancel your subscription, go to 'Account Settings' and select 'Cancel Subscription'.",
    language: "English",
    purpose: "Account Management",
    subpurpose: "Subscription",
    user: "kelly.davis@example.com",
    userId: "user606",
  },
  {
    id: "10",
    timeSend: "2024-01-09T14:15:00Z",
    channel: "Chatbot",
    question: "How do I change my email address?",
    answer:
      "To change your email address, go to 'Account Settings' and update your contact details.",
    language: "English",
    purpose: "Account Management",
    subpurpose: "Email Change",
    user: "peter.harris@example.com",
    userId: "user707",
  },
  {
    id: "11",
    timeSend: "2024-01-10T11:30:00Z",
    channel: "Website",
    question: "What is the return policy?",
    answer:
      "Our return policy allows returns within 30 days of purchase with a valid receipt.",
    language: "English",
    purpose: "Returns Support",
    subpurpose: "Return Policy",
    user: "nancy.ward@example.com",
    userId: "user808",
  },
  {
    id: "12",
    timeSend: "2024-01-11T13:00:00Z",
    channel: "Mobile App",
    question: "Can I track my package?",
    answer:
      "Yes, you can track your package by clicking on the 'Track Package' button in your orders section.",
    language: "English",
    purpose: "Shipping Support",
    subpurpose: "Package Tracking",
    user: "steve.walker@example.com",
    userId: "user909",
  },
  {
    id: "13",
    timeSend: "2024-01-12T09:45:00Z",
    channel: "Email",
    question: "How do I update my password?",
    answer:
      "To update your password, go to 'Account Settings' and select 'Change Password'.",
    language: "English",
    purpose: "Account Management",
    subpurpose: "Password Update",
    user: "lucy.morris@example.com",
    userId: "user1010",
  },
  {
    id: "14",
    timeSend: "2024-01-13T16:20:00Z",
    channel: "Website",
    question: "How can I contact customer support?",
    answer:
      "You can contact customer support by calling our hotline or through the live chat feature on our website.",
    language: "English",
    purpose: "Customer Support",
    subpurpose: "Contact Information",
    user: "alice.jenkins@example.com",
    userId: "user1111",
  },
  {
    id: "15",
    timeSend: "2024-01-14T17:00:00Z",
    channel: "Mobile App",
    question: "Can I change my shipping address?",
    answer:
      "You can change your shipping address before the order is shipped. Go to 'My Orders' to update the address.",
    language: "English",
    purpose: "Order Support",
    subpurpose: "Address Change",
    user: "harry.fletcher@example.com",
    userId: "user1212",
  },
  {
    id: "16",
    timeSend: "2024-01-15T10:30:00Z",
    channel: "Chatbot",
    question: "Do you have a loyalty program?",
    answer:
      "Yes, we offer a loyalty program where you can earn points with every purchase. Check our website for more details.",
    language: "English",
    purpose: "Sales Inquiry",
    subpurpose: "Loyalty Program",
    user: "lisa.martin@example.com",
    userId: "user1313",
  },
  {
    id: "17",
    timeSend: "2024-01-16T14:15:00Z",
    channel: "Website",
    question: "What are your delivery options?",
    answer:
      "We offer standard, express, and same-day delivery options, depending on your location.",
    language: "English",
    purpose: "Shipping Support",
    subpurpose: "Delivery Options",
    user: "john.smith@example.com",
    userId: "user1414",
  },
  {
    id: "18",
    timeSend: "2024-01-17T09:30:00Z",
    channel: "Mobile App",
    question: "Can I save my payment details for future purchases?",
    answer:
      "Yes, you can save your payment details securely in your account settings for future purchases.",
    language: "English",
    purpose: "Account Management",
    subpurpose: "Payment Details",
    user: "olivia.brown@example.com",
    userId: "user1515",
  },
  {
    id: "19",
    timeSend: "2024-01-18T11:00:00Z",
    channel: "Email",
    question: "How do I cancel an order?",
    answer:
      "To cancel an order, go to 'My Orders' and select 'Cancel'. If the order has already been processed, you may need to contact support.",
    language: "English",
    purpose: "Order Support",
    subpurpose: "Order Cancellation",
    user: "james.harris@example.com",
    userId: "user1616",
  },
  {
    id: "20",
    timeSend: "2024-01-19T13:45:00Z",
    channel: "Chatbot",
    question: "Where can I find my order history?",
    answer:
      "Your order history can be found in the 'My Orders' section of your account.",
    language: "English",
    purpose: "Order Support",
    subpurpose: "Order History",
    user: "megan.wilson@example.com",
    userId: "user1717",
  },
];
